version: "2"

services:
  caliper:
    container_name: caliper
    build: .
    environment:
      - CALIPER_BIND_SUT=${SUT}
      - CALIPER_BIND_SDK=${SDK}
      - CALIPER_BENCHCONFIG=benchmarks/scenario/config.yaml
      - CALIPER_NETWORKCONFIG=${NETWORK}
      - ABSOLUTE_PATH=${PWD}
    volumes:
      - $PWD:$PWD
      - ./caliper:/hyperledger/caliper/workspace
      - /var/run/docker.sock:/var/run/docker.sock