version: "2"

services:
  caliper:
    container_name: caliper
    build: .
    environment:
      - CALIPER_BIND_SUT=fabric
      - CALIPER_BIND_SDK=1.4.1
      - CALIPER_BENCHCONFIG=benchmarks/scenario/config.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/fabric-go.yaml
      - ABSOLUTE_PATH=${PWD}
    volumes:
      - $PWD:$PWD
      - ./caliper:/hyperledger/caliper/workspace
      - /var/run/docker.sock:/var/run/docker.sock