version: "2"

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.3.0
    command: launch master
    networks:
      - caliper-dind
    environment:
      - CALIPER_BIND_SUT=${SUT}
      - CALIPER_BENCHCONFIG=benchmarks/scenario/config.yaml
      - CALIPER_NETWORKCONFIG=${NETWORK}
      - ABSOLUTE_PATH=${PWD}
    volumes:
      - $PWD:$PWD
      - ./caliper:/hyperledger/caliper/workspace
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  caliper-dind: